const { requestJson } = require("./github");

const REVIEW_MARKER = "<!-- maintainer-automation:pr-review:v1 -->";

function buildCommentBody(markdown, engine) {
  return `${REVIEW_MARKER}\n\n${markdown.trimEnd()}\n\n---\nGenerated by maintainer-bot (${engine} engine).\n`;
}

async function upsertReviewComment(pr, body, {
  token,
  fetchImpl = globalThis.fetch,
  apiRoot = "https://api.github.com",
  timeoutMs = 15000,
} = {}) {
  if (!token) {
    throw new Error("Posting a comment requires GITHUB_TOKEN or GH_TOKEN");
  }

  const base = `${apiRoot}/repos/${pr.owner}/${pr.repo}`;
  const commentsUrl = `${base}/issues/${pr.number}/comments?per_page=100`;
  const comments = await requestJson(commentsUrl, { token, fetchImpl, timeoutMs });
  const existing = Array.isArray(comments)
    ? comments.find((comment) => typeof comment.body === "string" && comment.body.includes(REVIEW_MARKER))
    : null;

  if (existing) {
    await requestJson(`${base}/issues/comments/${existing.id}`, {
      token,
      fetchImpl,
      timeoutMs,
      method: "PATCH",
      body: { body },
    });
    return { action: "updated", id: existing.id };
  }

  const created = await requestJson(`${base}/issues/${pr.number}/comments`, {
    token,
    fetchImpl,
    timeoutMs,
    method: "POST",
    body: { body },
  });
  return { action: "created", id: created?.id };
}

module.exports = {
  REVIEW_MARKER,
  buildCommentBody,
  upsertReviewComment,
};
